# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'bingely' do
  config = use_native_modules!

  # AppCheckCore (pulled in by @react-native-google-signin/google-signin's
  # native GoogleSignIn iOS pod) is a Swift pod whose dependencies -
  # GoogleUtilities and RecaptchaInterop - don't define modules by default.
  # Without this, `pod install` fails static-linking them with:
  # "cannot yet be integrated as static libraries ... which do not define
  # modules." This app doesn't set use_frameworks!, so it's on the default
  # static-library linkage, hence needing these two opted in explicitly
  # rather than via a global use_modular_headers!.
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
